package ex5

fun main(){
    val cachorro = Cachorro("Charles","Dachshund","Jéssica")
    cachorro.exibirInformacoes()
    println()
    cachorro.movimentar()
    cachorro.comer()
    cachorro.dormir()
    println()
    val cachorro1 = Cachorro("Diana","Rottweiler","Amanda")
    cachorro1.exibirInformacoes()
    println()
    cachorro1.movimentar()
    cachorro1.comer()
    cachorro1.dormir()
    println()

    val gato = Gato("Osvaldo","Siamês","Amanda")
    gato.exibirInformacoes()
    println()
    gato.movimentar()
    gato.comer()
    gato.dormir()
    println()
    val gato1 = Gato("Frederico","Frajola","Amanda")
    gato1.exibirInformacoes()
    println()
    gato1.movimentar()
    gato1.comer()
    gato1.dormir()
    println()

    val peixe = Peixe("Nemo","Peixe-Palhaço","Leandro")
    peixe.exibirInformacoes()
    println()
    peixe.movimentar()
    peixe.comer()
    peixe.dormir()
    println()
    val peixe1 = Peixe("Dory","Cirurgiões-Patela","Cleber")
    peixe1.exibirInformacoes()
    println()
    peixe1.movimentar()
    peixe1.comer()
    peixe1.dormir()
}